### PR TITLE
Yosabet front end

### PR DESCRIPTION
**Pull request by YosabetK**

### CODE REVIEW

**Review by Chronowork1 — APPROVED** [review]
Good Job :).

**Review by francisli — CHANGES_REQUESTED** [review]
I'm trying to review this branch, but this is what I see when I run it:

Screen Shot 2021-05-26 at 2 21 01 PM
Screen Shot 2021-05-26 at 2 20 29 PM

When I try to add a new plant, it just takes me back to the blank plants list screen...?

**Comment by francisli** [comment]
There are also now conflicts with main that need to be resolved...

**Comment by Chronowork1** [comment]
So Yosabet worked on the Signup page, Successpage and Failpage.
If you got to http://localhost:3000/successpage, http://localhost:3000/failpage, http://localhost:3000/signup, you'll see the changes.

**Comment by francisli** [comment]
@Chronowork1 the problem is, if some of the changes for those pages have now affected the homepage and others, it will break those others when merged into main.

There are also still conflicts with main that still need to be resolved...

**Comment by Chronowork1** [comment]
Alright Francis, final stretch of the fellowship, I think there is something wrong, there is no conflicts on my end for some reason. I know you are super busy, may I borrow 10 min of your time to finally fix this issue? Ideally around 11:00 am?

**Comment by francisli** [comment]
@Chronowork1 @YosabetK the conflicts are displayed right here in the PR...!

Screen Shot 2021-05-27 at 7 20 19 AM

**Review by francisli — APPROVED** [review]

**Pull request merged**
