### PR TITLE
Jian front end userside2

### PR DESCRIPTION
**Pull request by Chronowork1**
Polish Yosabet front-end in a better style.

### CODE REVIEW

**Comment by francisli** [comment]
@Chronowork1 once again, there are conflicts with with main that you'll need to resolve first...?

**Comment by Chronowork1** [comment]
I'm not sure why it's not letting me push the resolve conflict into this pr.

**Comment by francisli** [comment]
To resolve this conflict, you should be ON this branch on your computer, then merge main onto your branch (`git merge main`). The conflict occurs because, on main, you reverted yosabet's changes (deleting files), but you still have those files and made changes to them on the branch. So git doesn't know whether those files should be deleted or kept as edited. You need to resolve the conflicts by making sure that the files with your changes are kept and not deleted.

**Comment by Chronowork1** [comment]
Alright, I don't why but the first time couple time I try git merge main, it commented saying "Already up to date", but this time I did it, it finally worked.

**Review by francisli — APPROVED** [review]
@Chronowork1 approved...

**Comment by Chronowork1** [comment]
Awesome, thanks Francis!!!

**Pull request merged**
